#!/usr/bin/env bash
# Regenerate PROD_ALL_MIGRATIONS.sql by concatenating every numbered migration
# (0NN_*.sql) in order. Run from this Database/ directory after adding a migration:
#
#   bash _regen_prod_script.sh
#
# Every migration is individually guarded with existence checks, so the combined
# script is idempotent -- safe to run against a fresh or partly-migrated database.
set -euo pipefail
cd "$(dirname "$0")"

OUT="PROD_ALL_MIGRATIONS.sql"

{
  echo "-- ====================================================================="
  echo "-- CONSOLIDATED PRODUCTION DEPLOYMENT SCRIPT"
  echo "-- Transport Management System -- all schema migrations, in order."
  echo "--"
  echo "-- Generated by concatenating every Database/0NN_*.sql migration."
  echo "-- Every statement in every migration is guarded with an existence check,"
  echo "-- so this script is idempotent: safe to run against a fresh database OR"
  echo "-- one already partly migrated. It only creates what is missing and never"
  echo "-- drops or alters existing data."
  echo "--"
  echo "-- Target: SQL Server. DB: FleetMasterDb (each section runs USE FleetMasterDb)."
  echo "-- Run with:  sqlcmd -S <server> -U <user> -P <pwd> -i PROD_ALL_MIGRATIONS.sql"
  echo "--"
  echo "-- DO NOT EDIT BY HAND -- regenerate with Database/_regen_prod_script.sh"
  echo "-- Last generated: $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "-- ====================================================================="
  echo
  for f in $(ls 0[0-9][0-9]_*.sql | sort); do
    echo
    echo "-- #####################################################################"
    echo "-- ##  BEGIN  $f"
    echo "-- #####################################################################"
    echo
    cat "$f"
    echo
    echo "-- ##  END    $f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines, $(ls 0[0-9][0-9]_*.sql | wc -l) migrations)."
