-- =====================================================================
-- CONSOLIDATED PRODUCTION DEPLOYMENT SCRIPT
-- Transport Management System -- all schema migrations, in order.
--
-- Generated by concatenating every Database/0NN_*.sql migration.
-- Every statement in every migration is guarded with an existence check,
-- so this script is idempotent: safe to run against a fresh database OR
-- one already partly migrated. It only creates what is missing and never
-- drops or alters existing data.
--
-- Target: SQL Server. DB: FleetMasterDb (each section runs USE FleetMasterDb).
-- Run with:  sqlcmd -S <server> -U <user> -P <pwd> -i PROD_ALL_MIGRATIONS.sql
--
-- DO NOT EDIT BY HAND -- regenerate with Database/_regen_prod_script.sh
-- Last generated: 2026-09-06 00:42 UTC
-- =====================================================================


-- #####################################################################
-- ##  BEGIN  001_Schema.sql
-- #####################################################################

-- =====================================================================
-- Transportation Management System - FleetMasterDb schema (DB-first)
--
-- This script is the single source of truth for the database schema.
-- The EF Core entity classes under Models/ and the FleetDbContext
-- mapping are hand-kept in sync with this script. There are no EF
-- Core migrations in this project -- schema changes are made here
-- first, then applied with:
--
--   sqlcmd -S "(localdb)\MSSQLLocalDB" -d FleetMasterDb -i 001_Schema.sql
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

IF DB_ID('FleetMasterDb') IS NULL
BEGIN
    CREATE DATABASE FleetMasterDb;
END
GO

USE FleetMasterDb;
GO

-- ---------------------------------------------------------------------
-- Vehicles (Fleet Master)
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.Vehicles', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Vehicles
    (
        Id                          INT IDENTITY(1,1) NOT NULL,
        VehicleCode                 NVARCHAR(450)   NOT NULL,
        RegistrationNumber          NVARCHAR(450)   NOT NULL,
        VehicleType                 INT             NOT NULL,
        Make                        NVARCHAR(MAX)   NULL,
        Model                       NVARCHAR(MAX)   NULL,
        Variant                     NVARCHAR(MAX)   NULL,
        YearOfManufacture           INT             NULL,
        OwnershipType               INT             NOT NULL,
        FuelType                    INT             NOT NULL,
        LoadCapacity                DECIMAL(18,2)   NULL,
        LoadCapacityUnit            NVARCHAR(MAX)   NULL,
        ChassisNumber               NVARCHAR(MAX)   NULL,
        EngineNumber                NVARCHAR(MAX)   NULL,
        BodyType                    NVARCHAR(MAX)   NULL,
        AxleCount                   INT             NULL,
        TrailerType                 NVARCHAR(MAX)   NULL,
        ContainerLiftCapacity       DECIMAL(18,2)   NULL,
        SeatingCapacity             INT             NULL,
        RCNumber                    NVARCHAR(MAX)   NULL,
        RCExpiryDate                DATE            NULL,
        FitnessCertificateNo        NVARCHAR(MAX)   NULL,
        FitnessExpiryDate           DATE            NULL,
        RoutePermitNo               NVARCHAR(MAX)   NULL,
        PermitExpiryDate            DATE            NULL,
        InsurancePolicyNo           NVARCHAR(MAX)   NULL,
        InsuranceProvider           NVARCHAR(MAX)   NULL,
        InsuranceExpiryDate         DATE            NULL,
        PollutionCertNo             NVARCHAR(MAX)   NULL,
        PollutionCertExpiryDate     DATE            NULL,
        TaxPaidTill                 DATE            NULL,
        CurrentStatus                INT            NOT NULL,
        CurrentLocation              NVARCHAR(MAX)  NULL,
        AssignedDriver               NVARCHAR(MAX)  NULL,
        CurrentBookingReference      NVARCHAR(MAX)  NULL,
        CurrentOdometerReading       DECIMAL(18,2)  NULL,
        FuelConsumptionAverage       DECIMAL(18,2)  NULL,
        LastOilChangeDate            DATE           NULL,
        LastOilChangeOdometer        DECIMAL(18,2)  NULL,
        NextOilChangeDueDate         DATE           NULL,
        NextOilChangeDueOdometer     DECIMAL(18,2)  NULL,
        LastServiceDate              DATE           NULL,
        ServiceIntervalKm            DECIMAL(18,2)  NULL,
        ServiceIntervalMonths        INT            NULL,
        BatteryReplacementDate       DATE           NULL,
        NumberOfTyres                INT            NULL,
        PurchasePrice                DECIMAL(18,2)  NULL,
        DepreciationInfo             NVARCHAR(MAX)  NULL,
        RunningCostPerKm             DECIMAL(18,2)  NULL,
        FuelCostTracking             DECIMAL(18,2)  NULL,
        CreatedAt                    DATETIME2      NOT NULL CONSTRAINT DF_Vehicles_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt                    DATETIME2      NULL,
        CONSTRAINT PK_Vehicles PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Vehicles_VehicleCode ON dbo.Vehicles(VehicleCode);
    CREATE UNIQUE INDEX IX_Vehicles_RegistrationNumber ON dbo.Vehicles(RegistrationNumber);
END
GO

-- ---------------------------------------------------------------------
-- AlertRules
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.AlertRules', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AlertRules
    (
        Id                  INT IDENTITY(1,1) NOT NULL,
        VehicleId           INT             NOT NULL,
        DocumentCategory    INT             NOT NULL,
        ThresholdDays       INT             NOT NULL,
        Channel             INT             NOT NULL,
        RecipientRole       NVARCHAR(MAX)   NULL,
        Status              INT             NOT NULL,
        CONSTRAINT PK_AlertRules PRIMARY KEY (Id),
        CONSTRAINT FK_AlertRules_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_AlertRules_VehicleId ON dbo.AlertRules(VehicleId);
END
GO

-- ---------------------------------------------------------------------
-- BookingRecords
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.BookingRecords', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.BookingRecords
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        VehicleId       INT             NOT NULL,
        TripReference   NVARCHAR(MAX)   NOT NULL,
        StartDate       DATE            NOT NULL,
        EndDate         DATE            NULL,
        Status          INT             NOT NULL,
        Notes           NVARCHAR(MAX)   NULL,
        CONSTRAINT PK_BookingRecords PRIMARY KEY (Id),
        CONSTRAINT FK_BookingRecords_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_BookingRecords_VehicleId ON dbo.BookingRecords(VehicleId);
END
GO

-- ---------------------------------------------------------------------
-- MaintenanceRecords
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.MaintenanceRecords', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MaintenanceRecords
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        VehicleId       INT             NOT NULL,
        Type            INT             NOT NULL,
        Date            DATE            NOT NULL,
        Odometer        DECIMAL(18,2)   NULL,
        Description     NVARCHAR(MAX)   NULL,
        ServiceVendor   NVARCHAR(MAX)   NULL,
        Cost            DECIMAL(18,2)   NULL,
        CONSTRAINT PK_MaintenanceRecords PRIMARY KEY (Id),
        CONSTRAINT FK_MaintenanceRecords_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_MaintenanceRecords_VehicleId ON dbo.MaintenanceRecords(VehicleId);
END
GO

-- ---------------------------------------------------------------------
-- Tyres
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.Tyres', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Tyres
    (
        Id                      INT IDENTITY(1,1) NOT NULL,
        VehicleId               INT             NOT NULL,
        Position                INT             NOT NULL,
        BrandAndSize            NVARCHAR(MAX)   NULL,
        InstallationDate        DATE            NULL,
        InstallationOdometer    DECIMAL(18,2)   NULL,
        CurrentCondition        NVARCHAR(MAX)   NULL,
        LastRotationDate        DATE            NULL,
        CONSTRAINT PK_Tyres PRIMARY KEY (Id),
        CONSTRAINT FK_Tyres_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_Tyres_VehicleId ON dbo.Tyres(VehicleId);
END
GO

-- ---------------------------------------------------------------------
-- VehicleDocuments
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.VehicleDocuments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.VehicleDocuments
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        VehicleId       INT             NOT NULL,
        Category        INT             NOT NULL,
        FileName        NVARCHAR(MAX)   NOT NULL,
        ContentType     NVARCHAR(MAX)   NOT NULL,
        StoragePath     NVARCHAR(MAX)   NOT NULL,
        FileSizeBytes   BIGINT          NOT NULL,
        UploadedAt      DATETIME2       NOT NULL CONSTRAINT DF_VehicleDocuments_UploadedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_VehicleDocuments PRIMARY KEY (Id),
        CONSTRAINT FK_VehicleDocuments_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_VehicleDocuments_VehicleId ON dbo.VehicleDocuments(VehicleId);
END
GO

-- ---------------------------------------------------------------------
-- TyreReplacementHistories
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.TyreReplacementHistories', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TyreReplacementHistories
    (
        Id                      INT IDENTITY(1,1) NOT NULL,
        TyreId                  INT             NOT NULL,
        ReplacedDate            DATE            NOT NULL,
        OdometerAtReplacement   DECIMAL(18,2)   NULL,
        OldBrandAndSize         NVARCHAR(MAX)   NULL,
        NewBrandAndSize         NVARCHAR(MAX)   NULL,
        Reason                  NVARCHAR(MAX)   NULL,
        CONSTRAINT PK_TyreReplacementHistories PRIMARY KEY (Id),
        CONSTRAINT FK_TyreReplacementHistories_Tyres_TyreId FOREIGN KEY (TyreId)
            REFERENCES dbo.Tyres(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_TyreReplacementHistories_TyreId ON dbo.TyreReplacementHistories(TyreId);
END
GO

-- ---------------------------------------------------------------------
-- Users (per-deployment SaaS tenant users)
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.Users', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Users
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        Username        NVARCHAR(100)   NOT NULL,
        Email           NVARCHAR(200)   NOT NULL,
        PasswordHash    NVARCHAR(MAX)   NOT NULL,
        FullName        NVARCHAR(200)   NOT NULL,
        Role            INT             NOT NULL, -- 0=Admin, 1=FleetManager, 2=Viewer
        IsActive        BIT             NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT (1),
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_Users_CreatedAt DEFAULT (SYSUTCDATETIME()),
        LastLoginAt     DATETIME2       NULL,
        CONSTRAINT PK_Users PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Users_Username ON dbo.Users(Username);
    CREATE UNIQUE INDEX IX_Users_Email ON dbo.Users(Email);
END
GO

-- ---------------------------------------------------------------------
-- CompanyProfile (single-row branding for this client's deployment)
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.CompanyProfile', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CompanyProfile
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        CompanyName     NVARCHAR(200)   NOT NULL,
        LogoPath        NVARCHAR(MAX)   NULL,
        Address         NVARCHAR(500)   NULL,
        ContactEmail    NVARCHAR(200)   NULL,
        ContactPhone    NVARCHAR(50)    NULL,
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_CompanyProfile PRIMARY KEY (Id)
    );
END
GO

-- ##  END    001_Schema.sql


-- #####################################################################
-- ##  BEGIN  002_PlainTextPasswordsAndLoginHistory.sql
-- #####################################################################

-- =====================================================================
-- Migration 002: switch Users to plain-text passwords, add LoginHistory
--
-- NOTE ON PASSWORDS: at the user's explicit request, passwords are now
-- stored in plain text (Users.Password) instead of hashed. This is a
-- deliberate, documented deviation from best practice -- see the
-- conversation this was decided in. Do not "fix" this back to hashing
-- without checking with the project owner first, since it would break
-- every existing stored password (hashes are one-way).
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

-- ---------------------------------------------------------------------
-- Users: PasswordHash -> Password (plain text)
-- ---------------------------------------------------------------------
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.Users') AND name = 'PasswordHash')
BEGIN
    EXEC sp_rename 'dbo.Users.PasswordHash', 'Password', 'COLUMN';
    ALTER TABLE dbo.Users ALTER COLUMN Password NVARCHAR(200) NOT NULL;
END
GO

-- ---------------------------------------------------------------------
-- LoginHistory
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.LoginHistory', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.LoginHistory
    (
        Id                  INT IDENTITY(1,1) NOT NULL,
        UserId              INT             NULL,
        AttemptedUsername   NVARCHAR(100)   NOT NULL,
        IsSuccessful        BIT             NOT NULL,
        LoginAt             DATETIME2       NOT NULL CONSTRAINT DF_LoginHistory_LoginAt DEFAULT (SYSUTCDATETIME()),
        IpAddress            NVARCHAR(64)   NULL,
        DeviceId             NVARCHAR(100)  NULL,
        UserAgent             NVARCHAR(500) NULL,
        Browser               NVARCHAR(100) NULL,
        OperatingSystem        NVARCHAR(100) NULL,
        City                    NVARCHAR(100) NULL,
        Region                  NVARCHAR(100) NULL,
        Country                 NVARCHAR(100) NULL,
        CONSTRAINT PK_LoginHistory PRIMARY KEY (Id),
        CONSTRAINT FK_LoginHistory_Users_UserId FOREIGN KEY (UserId)
            REFERENCES dbo.Users(Id) ON DELETE SET NULL
    );
    CREATE INDEX IX_LoginHistory_UserId ON dbo.LoginHistory(UserId);
    CREATE INDEX IX_LoginHistory_LoginAt ON dbo.LoginHistory(LoginAt DESC);
END
GO

-- ##  END    002_PlainTextPasswordsAndLoginHistory.sql


-- #####################################################################
-- ##  BEGIN  003_DriversManagement.sql
-- #####################################################################

-- =====================================================================
-- Migration 003: Drivers management (profiles, documents, vehicle
-- assignments).
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

-- ---------------------------------------------------------------------
-- Drivers
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.Drivers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Drivers
    (
        Id                  INT IDENTITY(1,1) NOT NULL,
        DriverCode          NVARCHAR(450)   NOT NULL,
        FullName            NVARCHAR(MAX)   NOT NULL,
        PhoneNumber         NVARCHAR(MAX)   NOT NULL,
        Email               NVARCHAR(MAX)   NULL,
        DateOfBirth         DATE            NULL,
        Address             NVARCHAR(MAX)   NULL,
        LicenseNumber       NVARCHAR(450)   NOT NULL,
        LicenseType         NVARCHAR(MAX)   NULL,
        LicenseExpiryDate   DATE            NULL,
        Status              INT             NOT NULL,
        CreatedAt           DATETIME2       NOT NULL CONSTRAINT DF_Drivers_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt           DATETIME2       NULL,
        CONSTRAINT PK_Drivers PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Drivers_DriverCode ON dbo.Drivers(DriverCode);
    CREATE UNIQUE INDEX IX_Drivers_LicenseNumber ON dbo.Drivers(LicenseNumber);
END
GO

-- ---------------------------------------------------------------------
-- DriverDocuments
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.DriverDocuments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DriverDocuments
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        DriverId        INT             NOT NULL,
        Category        INT             NOT NULL,
        FileName        NVARCHAR(MAX)   NOT NULL,
        ContentType     NVARCHAR(MAX)   NOT NULL,
        StoragePath     NVARCHAR(MAX)   NOT NULL,
        FileSizeBytes   BIGINT          NOT NULL,
        UploadedAt      DATETIME2       NOT NULL CONSTRAINT DF_DriverDocuments_UploadedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_DriverDocuments PRIMARY KEY (Id),
        CONSTRAINT FK_DriverDocuments_Drivers_DriverId FOREIGN KEY (DriverId)
            REFERENCES dbo.Drivers(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_DriverDocuments_DriverId ON dbo.DriverDocuments(DriverId);
END
GO

-- ---------------------------------------------------------------------
-- DriverVehicleAssignments
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.DriverVehicleAssignments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DriverVehicleAssignments
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        DriverId        INT             NOT NULL,
        VehicleId       INT             NOT NULL,
        StartDate       DATE            NOT NULL,
        EndDate         DATE            NULL,
        Status          INT             NOT NULL,
        Notes           NVARCHAR(MAX)   NULL,
        CONSTRAINT PK_DriverVehicleAssignments PRIMARY KEY (Id),
        CONSTRAINT FK_DriverVehicleAssignments_Drivers_DriverId FOREIGN KEY (DriverId)
            REFERENCES dbo.Drivers(Id) ON DELETE CASCADE,
        CONSTRAINT FK_DriverVehicleAssignments_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_DriverVehicleAssignments_DriverId ON dbo.DriverVehicleAssignments(DriverId);
    CREATE INDEX IX_DriverVehicleAssignments_VehicleId ON dbo.DriverVehicleAssignments(VehicleId);
END
GO

-- ##  END    003_DriversManagement.sql


-- #####################################################################
-- ##  BEGIN  004_TripsManagement.sql
-- #####################################################################

-- =====================================================================
-- Migration 004: Trip / Booking management.
--
-- Replaces the old dbo.BookingRecords stub (a placeholder that predated
-- the real Drivers module) with a proper dbo.Trips table that references
-- both a Vehicle and a Driver.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

-- ---------------------------------------------------------------------
-- Trips
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.Trips', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Trips
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        TripCode        NVARCHAR(450)   NOT NULL,
        VehicleId       INT             NOT NULL,
        DriverId        INT             NOT NULL,
        Origin          NVARCHAR(MAX)   NOT NULL,
        Destination     NVARCHAR(MAX)   NOT NULL,
        StartDate       DATE            NOT NULL,
        EndDate         DATE            NULL,
        Status          INT             NOT NULL,
        Notes           NVARCHAR(MAX)   NULL,
        Revenue         DECIMAL(18,2)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_Trips_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_Trips PRIMARY KEY (Id),
        CONSTRAINT FK_Trips_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE,
        CONSTRAINT FK_Trips_Drivers_DriverId FOREIGN KEY (DriverId)
            REFERENCES dbo.Drivers(Id) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX IX_Trips_TripCode ON dbo.Trips(TripCode);
    CREATE INDEX IX_Trips_VehicleId ON dbo.Trips(VehicleId);
    CREATE INDEX IX_Trips_DriverId ON dbo.Trips(DriverId);
END
GO

-- ---------------------------------------------------------------------
-- Drop the old BookingRecords stub -- superseded by dbo.Trips above.
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.BookingRecords', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.BookingRecords;
END
GO

-- ##  END    004_TripsManagement.sql


-- #####################################################################
-- ##  BEGIN  005_MaintenanceWorkshop.sql
-- #####################################################################

-- =====================================================================
-- Migration 005: Maintenance & Workshop.
--
-- Adds standalone workshop job cards (dbo.WorkOrders) plus their parts /
-- materials line items (dbo.WorkOrderItems). A WorkOrder references a
-- Vehicle but is not a nested child of it (mirrors dbo.Trips). The
-- pre-existing dbo.MaintenanceRecords quick-log is left untouched.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

-- ---------------------------------------------------------------------
-- WorkOrders
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.WorkOrders', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.WorkOrders
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        WorkOrderCode   NVARCHAR(450)   NOT NULL,
        VehicleId       INT             NOT NULL,
        Type            INT             NOT NULL,
        Priority        INT             NOT NULL,
        Status          INT             NOT NULL,
        ReportedDate    DATE            NOT NULL,
        ScheduledDate   DATE            NULL,
        CompletedDate   DATE            NULL,
        Odometer        DECIMAL(18,2)   NULL,
        Workshop        NVARCHAR(MAX)   NULL,
        Description     NVARCHAR(MAX)   NULL,
        Notes           NVARCHAR(MAX)   NULL,
        LabourCost      DECIMAL(18,2)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_WorkOrders_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_WorkOrders PRIMARY KEY (Id),
        CONSTRAINT FK_WorkOrders_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX IX_WorkOrders_WorkOrderCode ON dbo.WorkOrders(WorkOrderCode);
    CREATE INDEX IX_WorkOrders_VehicleId ON dbo.WorkOrders(VehicleId);
END
GO

-- ---------------------------------------------------------------------
-- WorkOrderItems
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.WorkOrderItems', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.WorkOrderItems
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        WorkOrderId     INT             NOT NULL,
        Description     NVARCHAR(MAX)   NOT NULL,
        Quantity        DECIMAL(18,2)   NOT NULL,
        UnitCost        DECIMAL(18,2)   NOT NULL,
        CONSTRAINT PK_WorkOrderItems PRIMARY KEY (Id),
        CONSTRAINT FK_WorkOrderItems_WorkOrders_WorkOrderId FOREIGN KEY (WorkOrderId)
            REFERENCES dbo.WorkOrders(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_WorkOrderItems_WorkOrderId ON dbo.WorkOrderItems(WorkOrderId);
END
GO

-- ##  END    005_MaintenanceWorkshop.sql


-- #####################################################################
-- ##  BEGIN  006_CustomerMaster.sql
-- #####################################################################

-- =====================================================================
-- Migration 006: Customer / Client Master.
--
-- Adds a standalone dbo.Customers table -- the master list of billing
-- customers. Trips and (later) invoices reference a customer, so this
-- table has no parent of its own (mirrors dbo.Drivers).
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

-- ---------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------
IF OBJECT_ID('dbo.Customers', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Customers
    (
        Id                INT IDENTITY(1,1) NOT NULL,
        CustomerCode      NVARCHAR(450)   NOT NULL,
        Name              NVARCHAR(MAX)   NOT NULL,
        ContactPerson     NVARCHAR(MAX)   NULL,
        Phone             NVARCHAR(30)    NOT NULL,
        Email             NVARCHAR(MAX)   NULL,
        BillingAddress    NVARCHAR(MAX)   NULL,
        TaxNumber         NVARCHAR(MAX)   NULL,
        CreditLimit       DECIMAL(18,2)   NULL,
        PaymentTermsDays  INT             NULL,
        Status            INT             NOT NULL,
        Notes             NVARCHAR(MAX)   NULL,
        CreatedAt         DATETIME2       NOT NULL CONSTRAINT DF_Customers_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt         DATETIME2       NULL,
        CONSTRAINT PK_Customers PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Customers_CustomerCode ON dbo.Customers(CustomerCode);
END
GO

-- ##  END    006_CustomerMaster.sql


-- #####################################################################
-- ##  BEGIN  007_TripCustomerLink.sql
-- #####################################################################

-- =====================================================================
-- Migration 007: Link Trips to Customers.
--
-- Adds an optional dbo.Trips.CustomerId -> dbo.Customers(Id). A trip
-- does not require a customer (internal / repositioning runs have none),
-- so the column is nullable and the FK is ON DELETE SET NULL.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.Trips') AND name = 'CustomerId')
BEGIN
    ALTER TABLE dbo.Trips ADD CustomerId INT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Trips_Customers_CustomerId')
BEGIN
    ALTER TABLE dbo.Trips
        ADD CONSTRAINT FK_Trips_Customers_CustomerId FOREIGN KEY (CustomerId)
            REFERENCES dbo.Customers(Id) ON DELETE SET NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_Trips_CustomerId' AND object_id = OBJECT_ID('dbo.Trips'))
BEGIN
    CREATE INDEX IX_Trips_CustomerId ON dbo.Trips(CustomerId);
END
GO

-- ##  END    007_TripCustomerLink.sql


-- #####################################################################
-- ##  BEGIN  008_FuelManagement.sql
-- #####################################################################

-- =====================================================================
-- Migration 008: Fuel Management.
--
-- Adds dbo.FuelEntries -- one row per fuel fill. References a Vehicle
-- (required, cascade) and optionally a Driver and a Trip (both nullable,
-- ON DELETE SET NULL so removing a driver/trip keeps the fuel history).
--
-- Mileage / cost-per-km are derived at read time from the odometer gap
-- to the previous entry, so no computed columns are stored here beyond
-- TotalCost (Litres * RatePerLitre), which the API always recomputes.
--
-- FK note: TripId uses ON DELETE NO ACTION (not SET NULL) to avoid a
-- multiple-cascade-path conflict with Vehicles/Drivers, which already
-- cascade into Trips. TripsController nulls FuelEntries.TripId in code
-- before deleting a trip.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.FuelEntries', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.FuelEntries
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        FuelEntryCode   NVARCHAR(450)   NOT NULL,
        VehicleId       INT             NOT NULL,
        DriverId        INT             NULL,
        TripId          INT             NULL,
        Date            DATE            NOT NULL,
        OdometerReading DECIMAL(18,2)   NOT NULL,
        Litres          DECIMAL(18,2)   NOT NULL,
        RatePerLitre    DECIMAL(18,2)   NOT NULL,
        TotalCost       DECIMAL(18,2)   NOT NULL,
        FuelType        INT             NOT NULL,
        PaymentMode     INT             NOT NULL,
        StationName     NVARCHAR(MAX)   NULL,
        SlipNumber      NVARCHAR(MAX)   NULL,
        IsTankFull      BIT             NOT NULL CONSTRAINT DF_FuelEntries_IsTankFull DEFAULT (1),
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_FuelEntries_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_FuelEntries PRIMARY KEY (Id),
        CONSTRAINT FK_FuelEntries_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE,
        CONSTRAINT FK_FuelEntries_Drivers_DriverId FOREIGN KEY (DriverId)
            REFERENCES dbo.Drivers(Id) ON DELETE SET NULL,
        CONSTRAINT FK_FuelEntries_Trips_TripId FOREIGN KEY (TripId)
            REFERENCES dbo.Trips(Id) ON DELETE NO ACTION
    );
    CREATE UNIQUE INDEX IX_FuelEntries_FuelEntryCode ON dbo.FuelEntries(FuelEntryCode);
    CREATE INDEX IX_FuelEntries_VehicleId_Date ON dbo.FuelEntries(VehicleId, Date);
    CREATE INDEX IX_FuelEntries_DriverId ON dbo.FuelEntries(DriverId);
    CREATE INDEX IX_FuelEntries_TripId ON dbo.FuelEntries(TripId);
END
GO

-- ##  END    008_FuelManagement.sql


-- #####################################################################
-- ##  BEGIN  009_TripExpenses.sql
-- #####################################################################

-- =====================================================================
-- Migration 009: Trip expenses.
--
-- Adds dbo.TripExpenses -- cost lines against a trip (toll, parking,
-- loading/unloading, driver allowance, en-route repair, fine, etc.).
-- A child of dbo.Trips, ON DELETE CASCADE (mirrors dbo.WorkOrderItems).
--
-- Per-trip P&L (revenue - fuel - expenses - driver pay) is computed at
-- read time by TripsController, so nothing is stored for it here.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.TripExpenses', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TripExpenses
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        TripId          INT             NOT NULL,
        Category        INT             NOT NULL,
        Amount          DECIMAL(18,2)   NOT NULL,
        Date            DATE            NOT NULL,
        PaidBy          INT             NOT NULL,
        ReceiptNumber   NVARCHAR(MAX)   NULL,
        Notes           NVARCHAR(MAX)   NULL,
        CONSTRAINT PK_TripExpenses PRIMARY KEY (Id),
        CONSTRAINT FK_TripExpenses_Trips_TripId FOREIGN KEY (TripId)
            REFERENCES dbo.Trips(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_TripExpenses_TripId ON dbo.TripExpenses(TripId);
END
GO

-- ##  END    009_TripExpenses.sql


-- #####################################################################
-- ##  BEGIN  010_Billing.sql
-- #####################################################################

-- =====================================================================
-- Migration 010: Billing & Invoicing (Accounts Receivable).
--
-- dbo.Invoices          -- one invoice raised against a customer
-- dbo.InvoiceLines      -- child lines (ON DELETE CASCADE)
-- dbo.Payments          -- receipts against an invoice (ON DELETE CASCADE)
--
-- Money fields (SubTotal / TaxAmount / Total / AmountPaid / Balance) and
-- the effective status (Paid / PartiallyPaid) are computed at read time
-- by InvoiceMapper, so only the raw inputs are stored: line qty/price,
-- Invoice.TaxPercent, payment amounts, and the user-set Status
-- (Draft / Sent / Cancelled).
--
-- InvoiceLines.TripId is a SOFT link (indexed, no FK): an issued invoice
-- is a frozen record, so deleting a trip must not cascade into or mutate
-- it, and there is no multi-cascade-path conflict with Trips.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.Invoices', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Invoices
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        InvoiceNumber   NVARCHAR(450)   NOT NULL,
        CustomerId      INT             NOT NULL,
        InvoiceDate     DATE            NOT NULL,
        DueDate         DATE            NOT NULL,
        Status          INT             NOT NULL,
        TaxPercent      DECIMAL(9,4)    NOT NULL CONSTRAINT DF_Invoices_TaxPercent DEFAULT (0),
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_Invoices_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_Invoices PRIMARY KEY (Id),
        CONSTRAINT FK_Invoices_Customers_CustomerId FOREIGN KEY (CustomerId)
            REFERENCES dbo.Customers(Id) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX IX_Invoices_InvoiceNumber ON dbo.Invoices(InvoiceNumber);
    CREATE INDEX IX_Invoices_CustomerId ON dbo.Invoices(CustomerId);
END
GO

IF OBJECT_ID('dbo.InvoiceLines', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.InvoiceLines
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        InvoiceId       INT             NOT NULL,
        TripId          INT             NULL,
        Description     NVARCHAR(MAX)   NOT NULL,
        Quantity        DECIMAL(18,2)   NOT NULL,
        UnitPrice       DECIMAL(18,2)   NOT NULL,
        CONSTRAINT PK_InvoiceLines PRIMARY KEY (Id),
        CONSTRAINT FK_InvoiceLines_Invoices_InvoiceId FOREIGN KEY (InvoiceId)
            REFERENCES dbo.Invoices(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_InvoiceLines_InvoiceId ON dbo.InvoiceLines(InvoiceId);
    CREATE INDEX IX_InvoiceLines_TripId ON dbo.InvoiceLines(TripId);
END
GO

IF OBJECT_ID('dbo.Payments', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Payments
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        InvoiceId       INT             NOT NULL,
        Date            DATE            NOT NULL,
        Amount          DECIMAL(18,2)   NOT NULL,
        Mode            INT             NOT NULL,
        Reference       NVARCHAR(MAX)   NULL,
        Notes           NVARCHAR(MAX)   NULL,
        CONSTRAINT PK_Payments PRIMARY KEY (Id),
        CONSTRAINT FK_Payments_Invoices_InvoiceId FOREIGN KEY (InvoiceId)
            REFERENCES dbo.Invoices(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_Payments_InvoiceId ON dbo.Payments(InvoiceId);
END
GO

-- ##  END    010_Billing.sql


-- #####################################################################
-- ##  BEGIN  011_ComplianceAlerts.sql
-- #####################################################################

-- =====================================================================
-- Migration 011: Compliance Alert Configuration + Delivery Log.
--
-- dbo.AlertConfigs  -- which document types / entity types to watch,
--                       lead-time (threshold days), recipient emails
-- dbo.AlertLog      -- what was actually emailed, when -- dedupe so the
--                       daily hosted service doesn't resend the same
--                       (entity, document, expiry date, severity) twice
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.AlertConfigs', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AlertConfigs
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        EntityType      INT             NULL,   -- NULL = Vehicle + Driver
        DocumentType    NVARCHAR(100)   NULL,   -- NULL = every document type
        ThresholdDays   INT             NOT NULL,
        RecipientEmails NVARCHAR(500)   NOT NULL,
        IsActive        BIT             NOT NULL CONSTRAINT DF_AlertConfigs_IsActive DEFAULT (1),
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_AlertConfigs_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_AlertConfigs PRIMARY KEY (Id)
    );
END
GO

IF OBJECT_ID('dbo.AlertLog', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.AlertLog
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        EntityType      INT             NOT NULL,
        EntityId        INT             NOT NULL,
        DocumentType    NVARCHAR(100)   NOT NULL,
        ExpiryDate      DATE            NOT NULL,
        Severity        INT             NOT NULL,
        RecipientEmails NVARCHAR(500)   NOT NULL,
        SentAt          DATETIME2       NOT NULL CONSTRAINT DF_AlertLog_SentAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_AlertLog PRIMARY KEY (Id)
    );
    -- Dedupe key: never re-send the same (entity, document, expiry, severity) combo.
    CREATE UNIQUE INDEX IX_AlertLog_Dedupe ON dbo.AlertLog(EntityType, EntityId, DocumentType, ExpiryDate, Severity);
END
GO

-- ##  END    011_ComplianceAlerts.sql


-- #####################################################################
-- ##  BEGIN  012_TyreManagement.sql
-- #####################################################################

-- =====================================================================
-- Migration 012: Tyre Management (promote to full module).
--
-- Extends dbo.Tyres into a standalone asset that can exist off any
-- vehicle ("in stock") -- VehicleId becomes nullable, ON DELETE switches
-- from CASCADE to SET NULL so a tyre's life history outlives the vehicle
-- it was last fitted to. App code (VehiclesController.Delete) unassigns a
-- vehicle's tyres back to stock before the delete, so Status stays
-- consistent with VehicleId even though the FK itself only nulls the column.
--
-- New dbo.TyreEvents is the full lifecycle log (Fit/Remove/Rotate/Retread/
-- Inspect/Scrap) for the new standalone Tyre module. The existing
-- dbo.TyreReplacementHistory table is untouched -- it keeps feeding the
-- "Replacements" list already on the vehicle editor's Tyres tab.
--
-- "Stock" (module spec's dbo.TyreStock) is modeled as Tyre rows with
-- VehicleId IS NULL rather than a separate table -- one asset table for a
-- tyre's whole life, no copy-in/copy-out dance when it's pulled or refitted.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('dbo.Tyres') AND name = 'VehicleId' AND is_nullable = 0)
BEGIN
    ALTER TABLE dbo.Tyres DROP CONSTRAINT FK_Tyres_Vehicles_VehicleId;
    ALTER TABLE dbo.Tyres ALTER COLUMN VehicleId INT NULL;
    ALTER TABLE dbo.Tyres ADD CONSTRAINT FK_Tyres_Vehicles_VehicleId FOREIGN KEY (VehicleId)
        REFERENCES dbo.Vehicles(Id) ON DELETE SET NULL;
END
GO

IF COL_LENGTH('dbo.Tyres', 'SerialNumber') IS NULL
    ALTER TABLE dbo.Tyres ADD SerialNumber NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.Tyres', 'Pattern') IS NULL
    ALTER TABLE dbo.Tyres ADD Pattern NVARCHAR(100) NULL;
GO
IF COL_LENGTH('dbo.Tyres', 'PurchaseDate') IS NULL
    ALTER TABLE dbo.Tyres ADD PurchaseDate DATE NULL;
GO
IF COL_LENGTH('dbo.Tyres', 'PurchaseCost') IS NULL
    ALTER TABLE dbo.Tyres ADD PurchaseCost DECIMAL(18,2) NULL;
GO
IF COL_LENGTH('dbo.Tyres', 'Status') IS NULL
    ALTER TABLE dbo.Tyres ADD Status INT NOT NULL CONSTRAINT DF_Tyres_Status DEFAULT (1); -- 1 = Fitted (existing rows are all currently-fitted tyres)
GO
IF COL_LENGTH('dbo.Tyres', 'TotalDistanceRunCarried') IS NULL
    ALTER TABLE dbo.Tyres ADD TotalDistanceRunCarried DECIMAL(18,2) NOT NULL CONSTRAINT DF_Tyres_TotalDistanceRunCarried DEFAULT (0);
GO
IF COL_LENGTH('dbo.Tyres', 'CreatedAt') IS NULL
    ALTER TABLE dbo.Tyres ADD CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Tyres_CreatedAt DEFAULT (SYSUTCDATETIME());
GO
IF COL_LENGTH('dbo.Tyres', 'UpdatedAt') IS NULL
    ALTER TABLE dbo.Tyres ADD UpdatedAt DATETIME2 NULL;
GO

IF OBJECT_ID('dbo.TyreEvents', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TyreEvents
    (
        Id          INT IDENTITY(1,1) NOT NULL,
        TyreId      INT             NOT NULL,
        EventType   INT             NOT NULL,
        EventDate   DATE            NOT NULL,
        VehicleId   INT             NULL,   -- soft snapshot, no FK
        Position    INT             NULL,
        Odometer    DECIMAL(18,2)   NULL,
        Cost        DECIMAL(18,2)   NULL,
        Notes       NVARCHAR(MAX)   NULL,
        CreatedAt   DATETIME2       NOT NULL CONSTRAINT DF_TyreEvents_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_TyreEvents PRIMARY KEY (Id),
        CONSTRAINT FK_TyreEvents_Tyres_TyreId FOREIGN KEY (TyreId)
            REFERENCES dbo.Tyres(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_TyreEvents_TyreId ON dbo.TyreEvents(TyreId);
END
GO

-- ##  END    012_TyreManagement.sql


-- #####################################################################
-- ##  BEGIN  013_PartsInventory.sql
-- #####################################################################

-- =====================================================================
-- Migration 013: Spare Parts Inventory / Stores.
--
-- dbo.Parts           -- part master: number, name, unit, reorder level, standard cost
-- dbo.StockMovements  -- receipt / issue / adjust log against a Part; on-hand
--                         qty and stock value are computed at read time
--                         (PartMapper), not stored.
--
-- dbo.WorkOrderItems gains an optional PartId: issuing a work-order line
-- against a stocked part auto-creates an Issue StockMovement, tracked back
-- via the new StockMovementId (soft link) so editing/deleting the line keeps
-- on-hand qty in sync (see WorkOrderItemsController).
--
-- Deferred: a dbo.Suppliers table -- that's Vendor master territory, owned
-- by module 11 (Vendor / Procurement / Purchase Orders) when it lands.
-- StockMovements carries a free-text SupplierName for receipts in the
-- meantime; ReferenceType/ReferenceId is generic so a future PurchaseOrder
-- reference doesn't need a schema change.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.Parts', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Parts
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        PartNumber      NVARCHAR(100)   NOT NULL,
        Name            NVARCHAR(200)   NOT NULL,
        Unit            NVARCHAR(30)    NOT NULL CONSTRAINT DF_Parts_Unit DEFAULT ('pcs'),
        ReorderLevel    DECIMAL(18,2)   NOT NULL CONSTRAINT DF_Parts_ReorderLevel DEFAULT (0),
        StandardCost    DECIMAL(18,2)   NULL,
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_Parts_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_Parts PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Parts_PartNumber ON dbo.Parts(PartNumber);
END
GO

IF OBJECT_ID('dbo.StockMovements', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.StockMovements
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        PartId          INT             NOT NULL,
        MovementType    INT             NOT NULL,
        Quantity        DECIMAL(18,2)   NOT NULL,
        UnitCost        DECIMAL(18,2)   NULL,
        Date            DATE            NOT NULL,
        ReferenceType   INT             NOT NULL CONSTRAINT DF_StockMovements_ReferenceType DEFAULT (0),
        ReferenceId     INT             NULL,
        SupplierName    NVARCHAR(150)   NULL,
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_StockMovements_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_StockMovements PRIMARY KEY (Id),
        CONSTRAINT FK_StockMovements_Parts_PartId FOREIGN KEY (PartId)
            REFERENCES dbo.Parts(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_StockMovements_PartId ON dbo.StockMovements(PartId);
END
GO

IF COL_LENGTH('dbo.WorkOrderItems', 'PartId') IS NULL
    ALTER TABLE dbo.WorkOrderItems ADD PartId INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_WorkOrderItems_Parts_PartId')
    ALTER TABLE dbo.WorkOrderItems ADD CONSTRAINT FK_WorkOrderItems_Parts_PartId FOREIGN KEY (PartId)
        REFERENCES dbo.Parts(Id) ON DELETE SET NULL;
GO
IF COL_LENGTH('dbo.WorkOrderItems', 'StockMovementId') IS NULL
    ALTER TABLE dbo.WorkOrderItems ADD StockMovementId INT NULL; -- soft link, no FK
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_WorkOrderItems_PartId')
    CREATE INDEX IX_WorkOrderItems_PartId ON dbo.WorkOrderItems(PartId);
GO

-- ##  END    013_PartsInventory.sql


-- #####################################################################
-- ##  BEGIN  014_DriverPayroll.sql
-- #####################################################################

-- =====================================================================
-- Migration 014: Driver Payroll / Settlements & Advances.
--
-- dbo.Drivers gains PayType + PayRate  -- per-driver pay configuration
-- dbo.DriverAdvances                   -- cash advances (khata); RecoveredAmount
--                                         tracks how much a pay run has clawed back
-- dbo.PayRuns                          -- one settlement for a driver over a period
-- dbo.PayRunLines                      -- per-trip / per-basis pay lines (child,
--                                         ON DELETE CASCADE)
--
-- Gross pay, net pay and advance-outstanding figures are computed at read
-- time by PayrollMapper, so only the raw inputs are stored: line qty/rate/
-- amount, PayRun.AllowancesTotal, PayRun.AdvanceRecovery, advance amounts
-- and their RecoveredAmount, and the user-set PayRun.Status.
--
-- PayRunLines.TripId is a SOFT link (indexed, no FK): a settled pay run is a
-- frozen record, so deleting a trip must not cascade into or mutate it, and
-- there is no multi-cascade-path conflict with Trips (same rationale as
-- InvoiceLines.TripId in migration 010).
--
-- The roadmap listed this as "013_DriverPayroll" -- renumbered to 014 because
-- 013 shipped as Parts Inventory.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF COL_LENGTH('dbo.Drivers', 'PayType') IS NULL
    ALTER TABLE dbo.Drivers ADD PayType INT NOT NULL CONSTRAINT DF_Drivers_PayType DEFAULT (0);
GO
IF COL_LENGTH('dbo.Drivers', 'PayRate') IS NULL
    ALTER TABLE dbo.Drivers ADD PayRate DECIMAL(18,2) NULL;
GO

IF OBJECT_ID('dbo.DriverAdvances', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.DriverAdvances
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        DriverId        INT             NOT NULL,
        Date            DATE            NOT NULL,
        Amount          DECIMAL(18,2)   NOT NULL,
        RecoveredAmount DECIMAL(18,2)   NOT NULL CONSTRAINT DF_DriverAdvances_Recovered DEFAULT (0),
        Reason          NVARCHAR(300)   NULL,
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_DriverAdvances_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_DriverAdvances PRIMARY KEY (Id),
        CONSTRAINT FK_DriverAdvances_Drivers_DriverId FOREIGN KEY (DriverId)
            REFERENCES dbo.Drivers(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_DriverAdvances_DriverId ON dbo.DriverAdvances(DriverId);
END
GO

IF OBJECT_ID('dbo.PayRuns', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PayRuns
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        PayRunCode      NVARCHAR(450)   NOT NULL,
        DriverId        INT             NOT NULL,
        PeriodStart     DATE            NOT NULL,
        PeriodEnd       DATE            NOT NULL,
        Status          INT             NOT NULL CONSTRAINT DF_PayRuns_Status DEFAULT (0),
        AllowancesTotal DECIMAL(18,2)   NOT NULL CONSTRAINT DF_PayRuns_Allowances DEFAULT (0),
        AdvanceRecovery DECIMAL(18,2)   NOT NULL CONSTRAINT DF_PayRuns_AdvanceRecovery DEFAULT (0),
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_PayRuns_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_PayRuns PRIMARY KEY (Id),
        CONSTRAINT FK_PayRuns_Drivers_DriverId FOREIGN KEY (DriverId)
            REFERENCES dbo.Drivers(Id) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX IX_PayRuns_PayRunCode ON dbo.PayRuns(PayRunCode);
    CREATE INDEX IX_PayRuns_DriverId ON dbo.PayRuns(DriverId);
END
GO

IF OBJECT_ID('dbo.PayRunLines', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PayRunLines
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        PayRunId        INT             NOT NULL,
        TripId          INT             NULL,
        Description     NVARCHAR(300)   NOT NULL,
        Basis           INT             NOT NULL CONSTRAINT DF_PayRunLines_Basis DEFAULT (4),
        Quantity        DECIMAL(18,2)   NOT NULL CONSTRAINT DF_PayRunLines_Quantity DEFAULT (1),
        Rate            DECIMAL(18,2)   NOT NULL CONSTRAINT DF_PayRunLines_Rate DEFAULT (0),
        Amount          DECIMAL(18,2)   NOT NULL,
        CONSTRAINT PK_PayRunLines PRIMARY KEY (Id),
        CONSTRAINT FK_PayRunLines_PayRuns_PayRunId FOREIGN KEY (PayRunId)
            REFERENCES dbo.PayRuns(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_PayRunLines_PayRunId ON dbo.PayRunLines(PayRunId);
    CREATE INDEX IX_PayRunLines_TripId ON dbo.PayRunLines(TripId);
END
GO

-- ##  END    014_DriverPayroll.sql


-- #####################################################################
-- ##  BEGIN  015_Tracking.sql
-- #####################################################################

-- =====================================================================
-- Migration 015: GPS / Live Tracking integration.
--
-- dbo.VehiclePositions -- raw position reports, one row per fix. The webhook
--                          (POST api/tracking/ingest) writes here; older rows
--                          past Tracking:MaxHotPositionsPerVehicle are pruned
--                          on ingest so the "hot" set stays small.
-- dbo.Geofences        -- named Circle (centre + radius) or Polygon (JSON
--                          [{lat,lng},...]) areas.
-- dbo.GeofenceEvents   -- Enter / Exit transitions, derived on ingest by
--                          comparing each fix against the previous state.
--
-- Provider-agnostic: the ingest endpoint takes a normalised report shape and
-- matches on VehicleId. A real telematics provider is wired by an adapter
-- that maps its payload/device-id to that shape -- no schema change needed.
-- The polling BackgroundService in the roadmap stays deferred until a
-- provider is chosen (nothing to poll yet), same as the SMS channel.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.VehiclePositions', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.VehiclePositions
    (
        Id              BIGINT IDENTITY(1,1) NOT NULL,
        VehicleId       INT             NOT NULL,
        Latitude        DECIMAL(9,6)    NOT NULL,
        Longitude       DECIMAL(9,6)    NOT NULL,
        SpeedKph        DECIMAL(6,2)    NULL,
        Heading         DECIMAL(6,2)    NULL,
        Ignition        BIT             NULL,
        DeviceTimeUtc   DATETIME2       NOT NULL,
        Source          NVARCHAR(50)    NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_VehiclePositions_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_VehiclePositions PRIMARY KEY (Id),
        CONSTRAINT FK_VehiclePositions_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE CASCADE
    );
    CREATE INDEX IX_VehiclePositions_Vehicle_DeviceTime
        ON dbo.VehiclePositions(VehicleId, DeviceTimeUtc DESC);
END
GO

IF OBJECT_ID('dbo.Geofences', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Geofences
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        Name            NVARCHAR(150)   NOT NULL,
        Shape           INT             NOT NULL CONSTRAINT DF_Geofences_Shape DEFAULT (0), -- 0 Circle, 1 Polygon
        CenterLat       DECIMAL(9,6)    NULL,
        CenterLng       DECIMAL(9,6)    NULL,
        RadiusMeters    DECIMAL(10,2)   NULL,
        PolygonJson     NVARCHAR(MAX)   NULL,   -- [{"lat":..,"lng":..}, ...]
        IsActive        BIT             NOT NULL CONSTRAINT DF_Geofences_IsActive DEFAULT (1),
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_Geofences_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_Geofences PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Geofences_Name ON dbo.Geofences(Name);
END
GO

IF OBJECT_ID('dbo.GeofenceEvents', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.GeofenceEvents
    (
        Id              BIGINT IDENTITY(1,1) NOT NULL,
        GeofenceId      INT             NOT NULL,
        VehicleId       INT             NOT NULL,
        EventType       INT             NOT NULL,   -- 0 Enter, 1 Exit
        OccurredAtUtc   DATETIME2       NOT NULL,
        Latitude        DECIMAL(9,6)    NOT NULL,
        Longitude       DECIMAL(9,6)    NOT NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_GeofenceEvents_CreatedAt DEFAULT (SYSUTCDATETIME()),
        CONSTRAINT PK_GeofenceEvents PRIMARY KEY (Id),
        CONSTRAINT FK_GeofenceEvents_Geofences_GeofenceId FOREIGN KEY (GeofenceId)
            REFERENCES dbo.Geofences(Id) ON DELETE CASCADE,
        CONSTRAINT FK_GeofenceEvents_Vehicles_VehicleId FOREIGN KEY (VehicleId)
            REFERENCES dbo.Vehicles(Id) ON DELETE NO ACTION  -- avoid multi-cascade path (Geofences already cascades)
    );
    CREATE INDEX IX_GeofenceEvents_Vehicle_OccurredAt
        ON dbo.GeofenceEvents(VehicleId, OccurredAtUtc DESC);
    CREATE INDEX IX_GeofenceEvents_Geofence_Vehicle
        ON dbo.GeofenceEvents(GeofenceId, VehicleId, OccurredAtUtc DESC);
END
GO

-- ##  END    015_Tracking.sql


-- #####################################################################
-- ##  BEGIN  016_RouteRateContracts.sql
-- #####################################################################

-- =====================================================================
-- Migration 016: Route & Rate-Contract Management.
--
-- dbo.Routes         -- lane master: origin, destination, distance, a
--                        standard rate used as the trip-revenue default when
--                        no customer contract applies.
-- dbo.RateContracts  -- customer x route (x optional vehicle type) -> rate,
--                        with a validity window. The most specific contract
--                        valid on the trip's start date wins.
--
-- dbo.Trips gains a nullable RouteId (ON DELETE SET NULL): picking a route on
-- the trip editor fills origin/destination and suggests revenue from the
-- resolved rate (see RateContractsController.Quote). Existing trips keep
-- their free-text origin/destination and are unaffected.
--
-- The entity is modelled as `RouteMaster` in code (table still `Routes`) to
-- avoid clashing with Microsoft.AspNetCore.Mvc.RouteAttribute in controllers.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.Routes', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Routes
    (
        Id                      INT IDENTITY(1,1) NOT NULL,
        RouteCode               NVARCHAR(450)   NOT NULL,
        Name                    NVARCHAR(200)   NULL,
        Origin                  NVARCHAR(150)   NOT NULL,
        Destination             NVARCHAR(150)   NOT NULL,
        DistanceKm              DECIMAL(10,2)   NULL,
        EstimatedDurationHours  DECIMAL(6,2)    NULL,
        StandardRate            DECIMAL(18,2)   NULL,
        IsActive                BIT             NOT NULL CONSTRAINT DF_Routes_IsActive DEFAULT (1),
        Notes                   NVARCHAR(MAX)   NULL,
        CreatedAt               DATETIME2       NOT NULL CONSTRAINT DF_Routes_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt               DATETIME2       NULL,
        CONSTRAINT PK_Routes PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Routes_RouteCode ON dbo.Routes(RouteCode);
    CREATE INDEX IX_Routes_OriginDestination ON dbo.Routes(Origin, Destination);
END
GO

IF OBJECT_ID('dbo.RateContracts', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.RateContracts
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        ContractCode    NVARCHAR(450)   NOT NULL,
        CustomerId      INT             NOT NULL,
        RouteId         INT             NOT NULL,
        VehicleType     INT             NULL,   -- NULL = applies to any vehicle type
        Rate            DECIMAL(18,2)   NOT NULL,
        RateBasis       INT             NOT NULL CONSTRAINT DF_RateContracts_Basis DEFAULT (0), -- 0 PerTrip, 1 PerKm
        ValidFrom       DATE            NOT NULL,
        ValidTo         DATE            NULL,
        IsActive        BIT             NOT NULL CONSTRAINT DF_RateContracts_IsActive DEFAULT (1),
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_RateContracts_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_RateContracts PRIMARY KEY (Id),
        CONSTRAINT FK_RateContracts_Customers_CustomerId FOREIGN KEY (CustomerId)
            REFERENCES dbo.Customers(Id) ON DELETE CASCADE,
        CONSTRAINT FK_RateContracts_Routes_RouteId FOREIGN KEY (RouteId)
            REFERENCES dbo.Routes(Id) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX IX_RateContracts_ContractCode ON dbo.RateContracts(ContractCode);
    CREATE INDEX IX_RateContracts_Customer_Route ON dbo.RateContracts(CustomerId, RouteId);
END
GO

IF COL_LENGTH('dbo.Trips', 'RouteId') IS NULL
    ALTER TABLE dbo.Trips ADD RouteId INT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_Trips_Routes_RouteId')
    ALTER TABLE dbo.Trips ADD CONSTRAINT FK_Trips_Routes_RouteId FOREIGN KEY (RouteId)
        REFERENCES dbo.Routes(Id) ON DELETE SET NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_Trips_RouteId')
    CREATE INDEX IX_Trips_RouteId ON dbo.Trips(RouteId);
GO

-- ##  END    016_RouteRateContracts.sql


-- #####################################################################
-- ##  BEGIN  017_VendorProcurement.sql
-- #####################################################################

-- =====================================================================
-- Migration 017: Vendor / Procurement / Purchase Orders.
--
-- dbo.Vendors             -- supplier master (parts supplier, workshop, fuel
--                            station, transporter, other). This is the
--                            "Suppliers" table module 13 deferred to here.
-- dbo.PurchaseOrders      -- one PO raised against a vendor
-- dbo.PurchaseOrderLines  -- child lines (ON DELETE CASCADE); optional PartId
--                            link to the Parts master (ON DELETE SET NULL).
--                            QuantityReceived tracks partial goods receipts.
--
-- Goods receipt: POST api/purchase-orders/{id}/receive increments each line's
-- QuantityReceived and, for lines linked to a stocked Part, writes a Receipt
-- StockMovement with ReferenceType = PurchaseOrder (2) / ReferenceId = the PO.
-- No schema change was needed for that -- StockMovements.ReferenceType/
-- ReferenceId were already generic (see migration 013).
--
-- Money (SubTotal / TaxAmount / Total) and the effective received status are
-- computed at read time (PurchaseOrderMapper); only raw inputs are stored.
--
-- Safe to re-run: every statement is guarded with an existence check.
-- =====================================================================

USE FleetMasterDb;
GO

IF OBJECT_ID('dbo.Vendors', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.Vendors
    (
        Id                  INT IDENTITY(1,1) NOT NULL,
        VendorCode          NVARCHAR(450)   NOT NULL,
        Name                NVARCHAR(200)   NOT NULL,
        VendorType          INT             NOT NULL CONSTRAINT DF_Vendors_Type DEFAULT (0),
        ContactPerson       NVARCHAR(150)   NULL,
        Phone               NVARCHAR(40)    NULL,
        Email               NVARCHAR(150)   NULL,
        Address             NVARCHAR(MAX)   NULL,
        TaxNumber           NVARCHAR(60)    NULL,
        PaymentTermsDays    INT             NULL,
        IsActive            BIT             NOT NULL CONSTRAINT DF_Vendors_IsActive DEFAULT (1),
        Notes               NVARCHAR(MAX)   NULL,
        CreatedAt           DATETIME2       NOT NULL CONSTRAINT DF_Vendors_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt           DATETIME2       NULL,
        CONSTRAINT PK_Vendors PRIMARY KEY (Id)
    );
    CREATE UNIQUE INDEX IX_Vendors_VendorCode ON dbo.Vendors(VendorCode);
    CREATE INDEX IX_Vendors_VendorType ON dbo.Vendors(VendorType);
END
GO

IF OBJECT_ID('dbo.PurchaseOrders', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PurchaseOrders
    (
        Id              INT IDENTITY(1,1) NOT NULL,
        PoNumber        NVARCHAR(450)   NOT NULL,
        VendorId        INT             NOT NULL,
        OrderDate       DATE            NOT NULL,
        ExpectedDate    DATE            NULL,
        Status          INT             NOT NULL CONSTRAINT DF_PurchaseOrders_Status DEFAULT (0),
        TaxPercent      DECIMAL(9,4)    NOT NULL CONSTRAINT DF_PurchaseOrders_TaxPercent DEFAULT (0),
        Notes           NVARCHAR(MAX)   NULL,
        CreatedAt       DATETIME2       NOT NULL CONSTRAINT DF_PurchaseOrders_CreatedAt DEFAULT (SYSUTCDATETIME()),
        UpdatedAt       DATETIME2       NULL,
        CONSTRAINT PK_PurchaseOrders PRIMARY KEY (Id),
        CONSTRAINT FK_PurchaseOrders_Vendors_VendorId FOREIGN KEY (VendorId)
            REFERENCES dbo.Vendors(Id) ON DELETE CASCADE
    );
    CREATE UNIQUE INDEX IX_PurchaseOrders_PoNumber ON dbo.PurchaseOrders(PoNumber);
    CREATE INDEX IX_PurchaseOrders_VendorId ON dbo.PurchaseOrders(VendorId);
END
GO

IF OBJECT_ID('dbo.PurchaseOrderLines', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PurchaseOrderLines
    (
        Id                  INT IDENTITY(1,1) NOT NULL,
        PurchaseOrderId     INT             NOT NULL,
        PartId              INT             NULL,
        Description         NVARCHAR(300)   NOT NULL,
        Quantity            DECIMAL(18,2)   NOT NULL,
        UnitPrice           DECIMAL(18,2)   NOT NULL,
        QuantityReceived    DECIMAL(18,2)   NOT NULL CONSTRAINT DF_PurchaseOrderLines_QtyRecd DEFAULT (0),
        CONSTRAINT PK_PurchaseOrderLines PRIMARY KEY (Id),
        CONSTRAINT FK_PurchaseOrderLines_PurchaseOrders_PurchaseOrderId FOREIGN KEY (PurchaseOrderId)
            REFERENCES dbo.PurchaseOrders(Id) ON DELETE CASCADE,
        CONSTRAINT FK_PurchaseOrderLines_Parts_PartId FOREIGN KEY (PartId)
            REFERENCES dbo.Parts(Id) ON DELETE SET NULL
    );
    CREATE INDEX IX_PurchaseOrderLines_PurchaseOrderId ON dbo.PurchaseOrderLines(PurchaseOrderId);
    CREATE INDEX IX_PurchaseOrderLines_PartId ON dbo.PurchaseOrderLines(PartId);
END
GO

-- ##  END    017_VendorProcurement.sql

